language: python
 python:
   - "3.6"
addons:
  apt:
    packages:
      - oracle-java8-installer 
sudo: false

cache:
  directories:
    - "$HOME/.m2"

install:
  - mvn install -DskipTests=true -DskipITs=true -Darchetype.test.skip=true -Dmaven.javadoc.skip=true -B -V

jobs:
  include:
    # 1.1 Semver check
    - stage: test
      jdk: openjdk11
      script: mvn verify -Pcheck-semantic-version -DskipTests=true -DskipITs=true -Darchetype.test.skip=true
      env: CHECK_SEMANTIC_VERSION=true

before_deploy:
  - pyenv global 3.6
  - pip install cloudsmith-cli

deploy:
  provider: script
  skip_cleanup: true
  script: cloudsmith push maven steviebeenzmvn/steviebeenz target/gba.jar
  on:
    branch: main
